WITH 
FEB28 AS(
SELECT DISTINCT ACT_ACCT_CD,SAFE_CAST(FI_OUTST_AGE AS INT64) AS MORA28
FROM `gcp-bia-tmps-vtr-dev-01.lla_temp_dna_tables.cwp_info_dna_fixed_history_v2` 
WHERE pd_mix_nm<>"0P" AND FI_OUTST_AGE IS NULL AND dt='2022-02-28'
)
,FEB27 AS(
SELECT DISTINCT ACT_ACCT_CD,SAFE_CAST(FI_OUTST_AGE AS INT64) AS FI_OUTST_AGE
FROM `gcp-bia-tmps-vtr-dev-01.lla_temp_dna_tables.cwp_info_dna_fixed_history_v2` 
WHERE pd_mix_nm<>"0P" AND dt='2022-02-27'
--AND SAFE_CAST(FI_OUTST_AGE AS FLOAT64)>90 
)
,MAR2 AS(
SELECT DISTINCT ACT_ACCT_CD,SAFE_CAST(FI_OUTST_AGE AS INT64) AS FI_OUTST_AGE
FROM `gcp-bia-tmps-vtr-dev-01.lla_temp_dna_tables.cwp_info_dna_fixed_history_v2` 
WHERE pd_mix_nm<>"0P" AND dt='2022-03-02'
--AND SAFE_CAST(FI_OUTST_AGE AS FLOAT64)>90 
)
,MM AS(
SELECT DISTINCT a.ACT_ACCT_CD,b.FI_OUTST_AGE AS MORA27,a.MORA28
FROM FEB28 a INNER JOIN FEB27 b ON A.act_acct_cd=b.act_acct_cd
GROUP BY FI_OUTST_AGE,a.ACT_ACCT_CD,MORA28
)
,FEBMAR AS(
SELECT DISTINCT *,b.FI_OUTST_AGE AS MORA3
--,CASE WHEN FI_OUTST_AGE<=90 THEN a.ACT_ACCT_CD END AS Menor90
--,CASE WHEN FI_OUTST_AGE>90 THEN a.ACT_ACCT_CD END AS Mayor90
FROM MM a INNER JOIN MAR2 b ON A.act_acct_cd=b.act_acct_cd
--GROUP BY FI_OUTST_AGE,a.ACT_ACCT_CD
)
,NN AS(
SELECT DISTINCT A.ACT_ACCT_CD
,CASE WHEN FI_OUTST_AGE<=90 THEN A.ACT_ACCT_CD END AS Menor90
,CASE WHEN FI_OUTST_AGE>90 THEN A.ACT_ACCT_CD END AS Mayor90
FROM FEB28 a INNER JOIN MAR2 b ON A.act_acct_cd=b.act_acct_cd
--GROUP BY FI_OUTST_AGE,a.ACT_ACCT_CD
)

SELECT COUNT(DISTINCT Menor90) AS MENOra90,COUNT(DISTINCT Mayor90) AS Mayora90
FROM NN
