SELECT  DISTINCT --DATE_TRUNC(PARSE_DATE("%Y%m%d",INV_PAYMT_DT),MONTH) AS MONTH
SAFE_CAST(dt AS DATE) AS MONTH
,INV_PAYMT_DT
,COUNT(DISTINCT ACCOUNTNO) 
FROM `gcp-bia-tmps-vtr-dev-01.lla_temp_dna_tables.cwp_info_dna_postpaid_history` 
WHERE BIZ_UNIT_D="B2C"
 AND SAFE_CAST(dt AS DATE)='2022-02-01'
GROUP BY MONTH,INV_PAYMT_DT
ORDER BY MONTH,INV_PAYMT_DT 
