select DISTINCT PD_VO_PROD_NM,
ROUND(VO_FI_TOT_MRC_AMT,2) AS VO_MRC,COUNT(DISTINCT ACT_ACCT_CD)
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-20_Historical_CRM_ene_2021_mar_2022_D` 
WHERE FECHA_EXTRACCION=DATE_TRUNC(FECHA_EXTRACCION,MONTH)
AND PD_VO_PROD_NM IN('TELEFONIA IP PYMES','TELEFONIA PLAN BASICO PYMES','TELEFONIA PLAN FULL PYMES','TELEFONIA PLAN FULL PYMES ADICIONAL','TELEFONIA PLAN BASICO PYMES ADICIONAL','TELEFONIA IP PYMES - ADICIONAL PYME')
--="001_SERVICIO BASICO ANALÓGICO"
GROUP BY 1,2
ORDER BY 1,2
