SELECT DATE_TRUNC(FECHA_EXTRACCION,MONTH) AS Month,FECHA_EXTRACCION, ACT_ACCT_CD,CST_CUST_NAME, C_CUST_AGE,PD_MIX_CD
,PD_VO_PROD_NM,VO_FI_TOT_MRC_AMT,VO_FI_TOT_MRC_AMT_DESC
,PD_BB_PROD_ID,BB_FI_TOT_MRC_AMT,BB_FI_TOT_MRC_AMT_DESC
,PD_TV_PROD_CD,TV_FI_TOT_MRC_AMT,TV_FI_TOT_MRC_AMT_DESC
,TOT_BILL_AMT,TOT_DESC_AMT,FI_OUTST_AGE
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-20_Historical_CRM_ene_2021_mar_2022_D` 
WHERE FECHA_EXTRACCION=DATE_TRUNC(FECHA_EXTRACCION,MONTH)
AND PD_TV_PROD_CD="001_SERVICIO BASICO ANALÓGICO"
order by 3,2
