WITH 
DueDays AS(
SELECT DISTINCT DATE_TRUNC(FECHA_EXTRACCION,MONTH) AS MONTH,FECHA_EXTRACCION,ACT_ACCT_CD,OLDEST_UNPAID_BILL_DT,FI_OUTST_AGE,DATE_DIFF(FECHA_EXTRACCION, OLDEST_UNPAID_BILL_DT, DAY) AS Mora
,CASE WHEN DATE_DIFF(FECHA_EXTRACCION, OLDEST_UNPAID_BILL_DT, DAY)=FI_OUTST_AGE THEN "OK" 
      WHEN OLDEST_UNPAID_BILL_DT IS NULL THEN "NOFECHAULTIMOPAGO"
ELSE NULL END AS MORACHECK
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-20_Historical_CRM_ene_2021_mar_2022_D` 
ORDER BY 2,1
)
SELECT DISTINCT MONTH,MORACHECK,COUNT(DISTINCT ACT_ACCT_CD) AS Records
FROM DueDays 
GROUP BY 1,2
ORDER BY 1,2
