SELECT DISTINCT 

PD_VO_PROD_NM,PD_VO_PROD_ID,ROUND(MAX(VO_FI_TOT_MRC_AMT),2) AS VO_MaxMRC,ROUND(MIN(VO_FI_TOT_MRC_AMT),2) AS VO_MinMRC,ROUND(AVG(VO_FI_TOT_MRC_AMT),2) AS VO_AvgMRC
--PD_BB_PROD_NM,PD_BB_PROD_ID,ROUND(MAX(BB_FI_TOT_MRC_AMT),2) AS BB_MaxMRC,ROUND(MIN(BB_FI_TOT_MRC_AMT),2) AS BB_MinMRC,ROUND(AVG(BB_FI_TOT_MRC_AMT),2) AS BB_AvgMRC
--PD_TV_PROD_CD,PD_TV_PROD_ID,ROUND(MAX(TV_FI_TOT_MRC_AMT),2) AS TV_MaxMRC,ROUND(MIN(TV_FI_TOT_MRC_AMT),2) AS TV_MinMRC,ROUND(AVG(TV_FI_TOT_MRC_AMT),2) AS TV_AvgMRC

,COUNT(DISTINCT ACT_ACCT_CD) AS Records
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-20_Historical_CRM_ene_2021_mar_2022_D`
GROUP BY 1,2
ORDER BY Records desc,1,2,3,4 
