/* Subconsulta que cruza los adelantos con las órdenes de servicio mediante el tiquete y el contrato*/
WITH 
CRUCEORDENESADELANTOS AS(
SELECT a.*, s.NO_ORDEN, s.FECHA_APERTURA,RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATO_ORDEN,
CASE WHEN a.adelanto = 5000 THEN Contrato END AS ADELANTOS5000,
CASE WHEN a.adelanto = 10000 THEN Contrato END AS ADELANTOS10000,
CASE WHEN a.adelanto > 10000 THEN Contrato END AS OTROS_PAGOS
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-03-08_ADELANTOS_2021_D` a
INNER JOIN  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` s
ON a.Orden = s.NO_ORDEN AND RIGHT(CONCAT('0000000000',s.NOMBRE_CONTRATO) ,10) = RIGHT(CONCAT('0000000000',a.CONTRATO) ,10)
WHERE RUBRO= "Diferidos / Adelantos" AND MONTO_PAGO <> 0
AND (a.Adelanto=5000 OR a.adelanto = 10000 OR adelanto > 10000)
ORDER BY a.Adelanto DESC
),
/* Subconsulta con las altas de cada mes de acuerdo a los filtros definidos*/
ALTAS AS (
SELECT RIGHT(CONCAT('0000000000',Contrato) ,10) AS CONTRATOALTA, Formato_Fecha
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-20_CR_ALTAS_V3_2021-01_A_2021-12_T`  
WHERE Tipo_Venta="Nueva"
AND (Tipo_Cliente = "PROGRAMA HOGARES CONECTADOS" OR Tipo_Cliente="RESIDENCIAL" OR Tipo_Cliente="EMPLEADO")
AND extract(year from Formato_Fecha) = 2021 
AND Subcanal__Venta<>"OUTBOUND PYMES" AND Subcanal__Venta<>"INBOUND PYMES" AND Subcanal__Venta<>"HOTELERO" AND Subcanal__Venta<>"PYMES – NETCOM" 
AND Tipo_Movimiento= "Altas por venta"
AND (Motivo="VENTA NUEVA " OR Motivo="VENTA")
GROUP BY Contrato, Formato_Fecha
),
/*Subconsulta que extrae los contratos que tuvieron fecha de alta en el CRM en 2021*/
ALTASCRM AS (
SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOALTACRM, ACT_ACCT_INST_DT
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
WHERE EXTRACT(YEAR FROM ACT_ACCT_INST_DT)=2021
GROUP BY ACT_ACCT_CD, ACT_ACCT_INST_DT
),
/*Cruce de las altas con altas del CRM*/
CRUCEALTAS AS (
SELECT x.CONTRATOALTA, x.Formato_Fecha
FROM ALTASCRM y INNER JOIN ALTAS x ON y.CONTRATOALTACRM=x.CONTRATOALTA
WHERE DATE(ACT_ACCT_INST_DT)=Formato_Fecha 
),
CHURNERSSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D`
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 ),
PRIMERCHURNSO AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, Min(FECHA_APERTURA) as PrimerChurnSO,
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
 AND FECHA_APERTURA IS NOT NULL
 GROUP BY CONTRATOSO
 ),
CHURNERSINVOLUNTARIOS AS
(SELECT DISTINCT RIGHT(CONCAT('0000000000',NOMBRE_CONTRATO) ,10) AS CONTRATOSO, FECHA_APERTURA,
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
 WHERE
  TIPO_ORDEN = "DESINSTALACION" 
  AND (ESTADO <> "CANCELADA" OR ESTADO <> "ANULADA")
  AND SUBMOTIVO = "MOROSIDAD"
 AND FECHA_APERTURA IS NOT NULL
 ),
CHURNTYPEFLAGSO AS(
    SELECT DISTINCT c. CONTRATOSO, c.PrimerChurnSO,
    CASE WHEN t.CONTRATOSO IS NULL THEN c.contratoso END AS VOLUNTARIO,
    CASE WHEN t.CONTRATOSO IS NOT NULL THEN c.CONTRATOSO END AS INVOLUNTARIO
    FROM PRIMERCHURNSO c LEFT JOIN CHURNERSINVOLUNTARIOS t ON c.CONTRATOSO = t.CONTRATOSO AND t.FECHA_APERTURA = c.PrimerChurnSO
),
CHURNERSCRM AS(
  SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOCRM, MAX(DATE(CST_CHRN_DT)) AS Maxfecha,DATE_TRUNC(Max(CST_CHRN_DT), MONTH) AS MesChurnF
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING DATE_TRUNC(Maxfecha, MONTH) = DATE_TRUNC(MAX(FECHA_EXTRACCION), MONTH)
),
FIRSTCHURN AS(
 SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS CONTRATOPCHURN, Min(DATE(CST_CHRN_DT)) AS PrimerChurn, DATE_TRUNC(Min(CST_CHRN_DT), MONTH) AS MesChurnP
    FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (YEAR FROM PrimerChurn) = 2021
),
REALCHURNERS AS(
 SELECT DISTINCT CONTRATOCRM AS CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP
 FROM CHURNERSCRM c  INNER JOIN FIRSTCHURN f ON c.CONTRATOCRM = f.CONTRATOPCHURN AND f.PrimerChurn <= c.MaxFecha
   GROUP BY CHURNER, MaxFecha, PrimerChurn, MesChurnF, MesChurnP),

CRUCECHURNERS AS(
SELECT DISTINCT s.CONTRATOSO, CHURNER, MaxFecha, MesChurnF, Voluntario, Involuntario
,CASE WHEN Voluntario IS NOT NULL THEN "Voluntario"
      WHEN Involuntario IS NOT NULL THEN "Involuntario" END AS ChurnType
FROM REALCHURNERS c LEFT JOIN CHURNERSSO s ON CONTRATOSO = CHURNER
AND c.MaxFecha >= s.FECHA_APERTURA AND date_diff(c.MaxFecha, s.FECHA_APERTURA, MONTH) <= 3
LEFT JOIN CHURNTYPEFLAGSO f ON s.CONTRATOSO = f.CONTRATOSO
GROUP BY contratoso, CHURNER, MesChurnF, MaxFecha, Voluntario, Involuntario
)
,ChurnersFinales AS(
SELECT DISTINCT CONTRATOSO AS ContratoChurn, MaxFecha
FROM CRUCECHURNERS
WHERE ChurnType="Involuntario"
)
,CRUCEFINAL AS(
SELECT o.*, a.*, c.*,
CASE WHEN CONTRATOCHURN IS NULL THEN CONTRATOALTA END AS NOCHURNERS,
CASE WHEN CONTRATOCHURN IS NOT NULL THEN CONTRATOALTA END AS CHURNERS,
CASE WHEN CONTRATOCHURN IS NULL AND CONTRATO_ORDEN IS NULL THEN CONTRATOALTA END AS NOCHURNERS_SIN_ADELANTO,
CASE WHEN CONTRATOCHURN IS NULL AND CONTRATO_ORDEN IS NOT NULL AND ADELANTOS5000 IS NOT NULL THEN CONTRATOALTA END AS NOCHURNERS_ADELANTO_5000,
CASE WHEN CONTRATOCHURN IS NULL AND CONTRATO_ORDEN IS NOT NULL AND ADELANTOS10000 IS NOT NULL THEN CONTRATOALTA END AS NOCHURNERS_ADELANTO_10000,
CASE WHEN CONTRATOCHURN IS NULL AND CONTRATO_ORDEN IS NOT NULL AND OTROS_PAGOS IS NOT NULL THEN CONTRATOALTA END AS NOCHURNERS_OTROS_PAGOS,
CASE WHEN CONTRATOCHURN IS NOT NULL AND CONTRATO_ORDEN IS NULL THEN CONTRATOALTA END AS CHURNERS_SIN_ADELANTO,
CASE WHEN CONTRATOCHURN IS NOT NULL AND CONTRATO_ORDEN IS NOT NULL AND ADELANTOS5000 IS NOT NULL THEN CONTRATOALTA END AS CHURNERS_ADELANTO_5000,
CASE WHEN CONTRATOCHURN IS NOT NULL AND CONTRATO_ORDEN IS NOT NULL AND ADELANTOS10000 IS NOT NULL THEN CONTRATOALTA END AS CHURNERS_ADELANTO_10000,
CASE WHEN CONTRATOCHURN IS NOT NULL AND CONTRATO_ORDEN IS NOT NULL AND OTROS_PAGOS IS NOT NULL THEN CONTRATOALTA END AS CHURNERS_OTROS_PAGOS
FROM CRUCEALTAS a LEFT JOIN CRUCEORDENESADELANTOS o ON o.CONTRATO_ORDEN = a.CONTRATOALTA AND ABS(DATE_DIFF(o.FECHA_APERTURA, a.Formato_Fecha, DAY)) <= 10 
LEFT JOIN ChurnersFinales c ON a.CONTRATOALTA = c.CONTRATOCHURN AND c.MaxFecha > a.Formato_Fecha AND DATE_DIFF(MAXFECHA, Formato_Fecha, DAY) <= 90
WHERE CONTRATOALTA IS NOT NULL
)
SELECT DATE_TRUNC(Formato_Fecha, MONTH) AS MESALTA,COUNT(DISTINCT CONTRATOALTA) AS NumContratosAltas, COUNT(DISTINCT Orden) AS NumTiquetesAdelantos, COUNT(DISTINCT Contrato) AS NumContratosAdelantos, COUNT (DISTINCT ADELANTOS5000) AS Num5000 , COUNT(DISTINCT ADELANTOS10000) AS Num10000
,COUNT(DISTINCT OTROS_PAGOS) AS NumOtrosPagos, (COUNT(DISTINCT ContratoAlta)- COUNT(DISTINCT Contrato)) as NumContratosNoAdelantos,
COUNT(DISTINCT NOCHURNERS) AS NC, COUNT(DISTINCT CHURNERS) AS C, COUNT (DISTINCT NOCHURNERS_SIN_ADELANTO) AS NC_SIN_ADELANTO, COUNT (DISTINCT NOCHURNERS_ADELANTO_5000) AS NC_5000, COUNT (DISTINCT NOCHURNERS_ADELANTO_10000) AS NC_10000, COUNT (DISTINCT NOCHURNERS_OTROS_PAGOS) AS NC_OTROSPAGOS, 
COUNT (DISTINCT CHURNERS_SIN_ADELANTO) AS C_SIN_ADELANTO, COUNT (DISTINCT CHURNERS_ADELANTO_5000) AS C_5000, COUNT(DISTINCT CHURNERS_ADELANTO_10000) AS C_10000, COUNT (DISTINCT CHURNERS_OTROS_PAGOS) AS C_OTROSPAGOS
FROM CRUCEFINAL
GROUP BY MESALTA
ORDER BY MESALTA


